spring.application.name=enrollment-service
server.port=8002

#MySQL Data base configuration
spring.datasource.url=jdbc:mysql://localhost:3306/studentmanagementsystem
spring.datasource.username=root
spring.datasource.password=mayank1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate

#Eureka registration properties
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Actuator properties
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

#CircuitBreaker Configuration
resilience4j.circuitbreaker.instances.studentValidate.base-config=default
resilience4j.circuitbreaker.instances.courseValidate.base-config=default
resilience4j.circuitbreaker.instances.getAllStudentsBreaker.base-config=default
resilience4j.circuitbreaker.instances.getAllCoursesBreaker.base-config=default

resilience4j.circuitbreaker.configs.default.register-health-indicator=true
resilience4j.circuitbreaker.configs.default.event-consumer-buffer-size=10
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=6s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.configs.default.sliding-window-type=count_based
resilience4j.circuitbreaker.configs.default.sliding-window-size=10

#Retry Config
resilience4j.retry.instances.studentValidateRetry.base-config=default
resilience4j.retry.instances.courseValidateRetry.base-config=default
resilience4j.retry.instances.getAllCourseRetry.base-config=default
resilience4j.retry.instances.getAllStudentRetry.base-config=default

resilience4j.retry.configs.default.max-attempts=4
resilience4j.retry.configs.default.wait-duration=3s
resilience4j.retry.configs.default.retry-exceptions[0]=com.enrollmentservice.enrollmentservice.exception.ServiceUnavailableException
logging.level.io.github.resilience4j.retry=debug

#timeout config
resilience4j.timelimiter.instances.getAllCourseTimeout.base-config=default
resilience4j.timelimiter.instances.getAllStudentTimeout.base-config=default
resilience4j.timelimiter.instances.studentValidateTimeout.base-config=default
resilience4j.timelimiter.instances.courseValidateTimeout.base-config=default

resilience4j.timelimiter.configs.default.timeout-duration=5s